
spring:
 datasource:
  password: psw
  url: jdbc:mysql://localhost:3306/serverdb
  username: usr
 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    formate_sql: true
  show-sql: true