
spring:
 datasource:
  password: 
  url: jdbc:mysql://localhost:3306/serverdb
  username: 
 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    formate_sql: true
  show-sql: true